[package]
name = "stegobench-cli"
description = "The stegobench command"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "stegobench"
path = "src/main.rs"

[dependencies]
stegobench-core = { path = "../stegobench-core" }
stegobench-metrics = { path = "../stegobench-metrics" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
