#!/usr/bin/env python3
# Author:  Daniel Iwugo
# Comment: Christ is King
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Daniel Iwugo
"""Build the starter corpus: six matched pairs, shipped, and not a measurement.

WHAT THIS IS FOR
----------------
On a fresh install `stegobench score` has nothing to score. The corpus it was
built for is 48 GB, the smallest published tier is about a gigabyte, and both
of those are a download away. So the tool that is supposed to tell you whether
your detector works does nothing at all until you have spent an hour getting
data, which is the wrong first five minutes.

This is the answer to that and nothing more: six covers, two arms, eighteen
images, built here so a first run walks a real corpus, checks a real pairing
rule, runs a real detector and prints a real result document.

WHY IT CANNOT BE MISTAKEN FOR A BENCHMARK RESULT
------------------------------------------------
Six covers is not a measurement. An AUC over eighteen images moves by a tenth
when one image changes, so a number from here says nothing about a detector and
everything about which six pictures were synthesised.

That is not left to a reader to notice. The registry entry beside this corpus
is marked `demonstration`, and a demonstration entry is forbidden by
`CorpusEntry::validate` from declaring the records digest that `stegobench
score` requires before it will mark a run `named`. So every run over this
corpus comes out `custom`, which `result-v1` already defines as "comparable
with itself and nothing else". No new field, no honour system.

WHY THE COVERS ARE SYNTHETIC
----------------------------
Every cover in the real corpus is a photograph with a licence, an artist and a
source URL attached, and none of that can be shipped inside a code repository:
the smallest published tier is a gigabyte, and a photograph carries an
attribution obligation that a file checked into a git tree would have to carry
with it. These are generated instead, from a fixed seed, by the same function
that builds the plugin self-test fixtures. They are smooth gradients plus mild
grain, which is closer to a photograph's statistics than noise or a flat field
and is still not a photograph. It is a second reason a number from here does
not transfer, and it is stated in the registry entry rather than buried.

THE PAIRING RULE HOLDS BY CONSTRUCTION
--------------------------------------
Every pair comes out of one array through one writer. The cover is written from
`cover`, the stego image from a copy of `cover` with some of its least
significant bits replaced, and both go through `make_fixtures.write_png` with
the same settings. Nothing else differs: same format, same dimensions, same bit
depth, same channel count, which is what `stegobench score` checks and would
report as confounded if it were not true.

The payload is a pure function of the cover's name, the tool and the rate, via
`payloads.payload_bytes`, which is the rule the real corpus follows and for the
reason that module records: a payload drawn from a running generator depends on
everything the build did before it, so nobody, including the people who built
it, can reproduce the bytes.

Usage::

    python3 corpora/starter/build.py --check     # rebuild and compare
    python3 corpora/starter/build.py --write     # rebuild in place
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "generators"))

from make_fixtures import clean_cover, write_png  # noqa: E402
from payloads import payload_bytes  # noqa: E402

#: Fixed. Two runs of this script produce byte-identical files, which is what
#: makes `--check` a test rather than a formality.
SEED = 20260928

#: Bumping this changes every payload here, exactly as `payloads.SCHEME` does
#: for the real corpus.
CORPUS_SEED = 20260928

#: Six. Enough for both sides of a measurement to exist and far too few for the
#: measurement to mean anything, which is the balance this corpus wants.
COVERS = 6

#: Bits per pixel, on the same axis the real spatial arms use.
RATES = (0.4, 0.1)

#: Named in the corpus rather than derived from a seed at read time, so the
#: train and test sides are a property of the cover and are inherited by
#: everything made from it. The same discipline the real tiers keep, and the
#: one `stegobench score` refuses a corpus for breaking.
SPLIT_SALT = "stegobench-starter-v1"

#: These images are generated by this script and ship inside this repository,
#: so they carry the repository's own licence. Not a guess and not a friendlier
#: label picked because a starter corpus deserves one: a grant nobody issued is
#: exactly what `docs/design/cover-source-licensing.md` catalogues going wrong.
LICENCE = "AGPL-3.0-or-later"
LICENCE_URL = "https://www.gnu.org/licenses/agpl-3.0.en.html"


def cover_name(index: int) -> str:
    """The stable name a record gives its own image.

    Deliberately not the name on disk. A packed release renames every member to
    its position, so a stego row joins back to its cover by the name the RECORD
    carries, and a starter corpus whose two names happened to agree would
    exercise a join the real corpus never takes.
    """
    return f"starter-{index:04d}.png"


def split_of(name: str) -> str:
    """Train or test, decided once, as a property of the cover."""
    material = f"{SPLIT_SALT}\x1f{name}".encode("utf-8")
    return "train" if hashlib.sha256(material).digest()[0] < 128 else "test"


def covers() -> list[np.ndarray]:
    """Six distinct textured greyscale covers from one seeded generator.

    `clean_cover` builds one field from a fixed formula, so calling it six times
    would give six pictures differing only in grain. Each is rolled by a
    different offset instead, which moves the phase of every component and gives
    genuinely different pictures out of the same deterministic source.
    """
    rng = np.random.default_rng(SEED)
    out = []
    for i in range(COVERS):
        field = clean_cover(rng)
        out.append(np.roll(np.roll(field, 37 * i, axis=0), 53 * i, axis=1))
    return out


def embed_lsb(cover: np.ndarray, rate_bpp: float, name: str, rate: float):
    """LSB replacement at `rate_bpp`, carrying a payload derived from the cover.

    Not `make_fixtures.embed_lsb`, and the difference is the point. That one
    draws its bits from whatever generator the caller passes, which is right for
    a smoke test and wrong for a corpus: the bits a given image carries would
    then depend on everything the build did before it. Here the payload comes
    from `payloads.payload_bytes`, so the same cover at the same rate carries
    the same bytes whatever order the build ran in.
    """
    flat = cover.reshape(-1)
    count = int(flat.size * rate_bpp)
    if count == 0:
        raise SystemExit(f"a rate of {rate_bpp} changes nothing in this cover")

    # Positions are drawn from the payload seed as well, so the whole arm is a
    # function of (cover, tool, rate) and of nothing else.
    seed = int.from_bytes(hashlib.sha256(
        f"{SPLIT_SALT}\x1f{name}\x1flsb\x1f{rate:.6f}".encode("utf-8")
    ).digest()[:8], "big")
    positions = np.random.default_rng(seed).choice(flat.size, size=count, replace=False)

    payload = payload_bytes(CORPUS_SEED, name, "lsb", rate, (count + 7) // 8)
    bits = np.unpackbits(np.frombuffer(payload, dtype=np.uint8))[:count]

    stego = flat.copy()
    stego[positions] = (stego[positions] & 0xFE) | bits
    changed = int(np.count_nonzero(stego != flat))
    if changed == 0:
        raise SystemExit(f"the embedding changed nothing in {name}")
    return stego.reshape(cover.shape), changed


def arm_name(rate: float) -> str:
    return f"lsb-{int(round(rate * 1000)):04d}"


def build(out: pathlib.Path) -> list[dict]:
    """Write the corpus under `out` and return its manifest rows, in order."""
    rows: list[dict] = []
    fields = covers()

    cover_dir = out / "covers"
    cover_dir.mkdir(parents=True, exist_ok=True)
    for index, field in enumerate(fields):
        name = cover_name(index)
        path = cover_dir / f"{index:06d}.png"
        digest = write_png(path, field)
        row = {
            "schema": "stegobench/manifest-v1",
            "file": name,
            "sha256": digest,
            "width": int(field.shape[1]),
            "height": int(field.shape[0]),
            "original_mime": "image/png",
            # True, and true because these were never anything else. Every
            # Pentimento cover says false here: it was a JPEG before it was
            # cropped, which is why thresholds calibrated there do not transfer.
            "pristine": True,
            "licence": LICENCE,
            "licence_url": LICENCE_URL,
            "capture_class": "synthetic",
            "capture_class_basis": "generated by corpora/starter/build.py",
            "split": split_of(name),
            "tier_order": index,
            "split_salt": SPLIT_SALT,
            "role": "clean",
        }
        (cover_dir / f"{index:06d}.json").write_text(
            json.dumps(row, sort_keys=True, indent=1) + "\n", encoding="utf-8"
        )
        rows.append(row)

    for rate in RATES:
        arm = arm_name(rate)
        arm_dir = out / arm
        arm_dir.mkdir(parents=True, exist_ok=True)
        for index, field in enumerate(fields):
            name = cover_name(index)
            stego, changed = embed_lsb(field, rate, name, rate)
            path = arm_dir / f"{index:06d}.png"
            digest = write_png(path, stego)
            row = {
                "file": f"{arm}-{index:04d}.png",
                "sha256": digest,
                "width": int(stego.shape[1]),
                "height": int(stego.shape[0]),
                "original_mime": "image/png",
                "pristine": True,
                "role": "stego",
                # The join back to the cover, by the name the cover's own record
                # gives it rather than by the name on disk.
                "source_png": name,
                "arm": arm,
                "tool": "lsb",
                "rate": rate,
                "rate_unit": "bpp",
                "domain": "spatial",
                "changed": changed,
                # Inherited, because a stego image is a derivative and a reader
                # who never opens the cover directory still has to be told what
                # governs the file in front of them.
                "licence": LICENCE,
                "licence_url": LICENCE_URL,
                "tier_order": index,
                "split_salt": SPLIT_SALT,
            }
            (arm_dir / f"{index:06d}.json").write_text(
                json.dumps(row, sort_keys=True, indent=1) + "\n", encoding="utf-8"
            )
            rows.append(row)

    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(HERE))
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rebuild in place")
    mode.add_argument("--check", action="store_true",
                      help="rebuild into a temporary directory and compare")
    args = ap.parse_args(argv)

    if args.check:
        import shutil
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            fresh = pathlib.Path(tmp) / "starter"
            rows = build(fresh)
            here = pathlib.Path(args.out)
            bad = []
            for path in sorted(fresh.rglob("*")):
                if path.is_dir():
                    continue
                mirror = here / path.relative_to(fresh)
                if not mirror.is_file():
                    bad.append(f"missing: {mirror}")
                elif mirror.read_bytes() != path.read_bytes():
                    bad.append(f"differs: {mirror}")
            shutil.rmtree(fresh, ignore_errors=True)
        if bad:
            print("the shipped starter corpus is not what this script builds:",
                  file=sys.stderr)
            for line in bad:
                print(f"  {line}", file=sys.stderr)
            return 1
        print(f"the shipped starter corpus matches this script: {len(rows)} rows")
        return 0

    out = pathlib.Path(args.out)
    rows = build(out)
    splits = {r["split"] for r in rows if r.get("role") == "clean"}
    if splits != {"train", "test"}:
        # A corpus with one side of the split is not one anybody can train and
        # evaluate on, and finding that out at score time is finding it out late.
        print(f"the covers landed on one side of the split only: {splits}",
              file=sys.stderr)
        return 1
    manifest = out / "manifest.jsonl"
    manifest.write_text(
        "".join(json.dumps(r, sort_keys=True) + "\n" for r in rows), encoding="utf-8"
    )
    total = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    print(f"{len(rows)} rows, {total} bytes under {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
