#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Daniel Iwugo
"""Payload bytes that depend on which image they are for, and on nothing else.

WHY THIS EXISTS
---------------
The corpus says it is rebuildable byte for byte. That was true of the adaptive
arms and false of the tool arms, and the reason is worth stating plainly
because it is easy to write again.

The tool builder created one generator for the whole run::

    rng = random.Random(args.seed)
    ...
    payload = rng.randbytes(payload_bytes)

A seeded generator is reproducible, which is why this looked finished. But the
stream is consumed in order, and the loop around it skips: it skips work
already done when resuming, it skips a cover the tool refused, and the number
of bytes drawn varies per image because it is a fraction of that image's
capacity. So the payload any given image receives depends on the entire history
of successes, failures and skips before it.

outguess refuses 1,884 of these covers and the build ran under a watchdog
across more than one session, so the shipped arms were certainly not produced
by one unbroken pass. Nobody, including the people who built it, could have
reproduced those bytes from the recorded seed.

THE RULE
--------
A payload is a pure function of the thing it is for. Same corpus seed, same
image, same tool, same rate, same bytes, whatever else the run did or did not
do, in whatever order, on whatever machine, resumed however many times.

Derived by hashing rather than by arithmetic on a loop index, because indices
collide when a corpus is rebuilt with covers added or removed, and a collision
here means two images silently sharing a payload.
"""
from __future__ import annotations

import hashlib

#: Bumping this changes every payload in the corpus. It exists so that a future
#: change to the derivation is a deliberate, visible, versioned act rather than
#: something that quietly invalidates a published dataset.
SCHEME = "pentimento-payload-v1"


def payload_seed(corpus_seed: int, image: str, tool: str, rate: float) -> bytes:
    """A 32 byte seed for one image, one tool and one rate.

    `image` is the stable name of the cover, not its position: positions move
    when a corpus gains or loses a cover, and a payload that moves with it
    cannot be checked against a published digest.
    """
    material = "\x1f".join((SCHEME, str(corpus_seed), image, tool, f"{rate:.6f}"))
    return hashlib.sha256(material.encode("utf-8")).digest()


def payload_bytes(corpus_seed: int, image: str, tool: str, rate: float,
                  length: int) -> bytes:
    """`length` bytes of payload for one image, tool and rate.

    Generated by counter mode over the seed rather than by seeding a
    `random.Random`, so the bytes do not depend on the Python version's
    Mersenne Twister implementation. A corpus that reproduces only on one
    interpreter is not reproducible in the sense the README claims.
    """
    if length < 0:
        raise ValueError(f"a payload cannot be {length} bytes long")
    seed = payload_seed(corpus_seed, image, tool, rate)
    out = bytearray()
    counter = 0
    while len(out) < length:
        out += hashlib.sha256(seed + counter.to_bytes(8, "big")).digest()
        counter += 1
    return bytes(out[:length])
